component_depth: 1
languages:
- java
exclude:
- ./addressbook/.*
- ./addressbook/bin/.*
- ./addressbook/bin/com/.*
- ./addressbook/bin/com/ivata/.*
- ./addressbook/bin/com/ivata/groupware/.*
- ./addressbook/bin/com/ivata/groupware/admin/.*
- ./addressbook/bin/com/ivata/groupware/admin/security/.*
- ./addressbook/bin/com/ivata/groupware/admin/security/addressbook/.*
- ./addressbook/bin/com/ivata/groupware/admin/security/right/.*
- ./addressbook/bin/com/ivata/groupware/admin/security/server/.*
- ./addressbook/bin/com/ivata/groupware/admin/security/struts/.*
- ./addressbook/bin/com/ivata/groupware/admin/setting/.*
- ./addressbook/bin/com/ivata/groupware/admin/setting/right/.*
- ./addressbook/bin/com/ivata/groupware/admin/setting/struts/.*
- ./addressbook/bin/com/ivata/groupware/business/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/address/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/address/country/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/person/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/person/employee/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/person/group/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/person/group/right/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/person/group/right/detail/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/person/group/tree/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/right/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/struts/.*
- ./addressbook/bin/com/ivata/groupware/business/addressbook/telecomaddress/.*
- ./addressbook/bin/com/ivata/groupware/navigation/.*
- ./addressbook/bin/com/ivata/groupware/navigation/menu/.*
- ./addressbook/bin/com/ivata/groupware/navigation/menu/item/.*
- ./addressbook/bin/com/ivata/groupware/navigation/menu/item/listener/.*
- ./addressbook/bin/com/ivata/groupware/navigation/struts/.*
- ./addressbook/bin/com/ivata/groupware/web/.*
- ./addressbook/bin/com/ivata/groupware/web/tag/.*
- ./addressbook/bin/com/ivata/groupware/web/tag/webgui/.*
- ./addressbook/bin/com/ivata/groupware/web/tag/webgui/tree/.*
- ./addressbook/bin/com/ivata/groupware/web/tree/.*
- ./addressbook/bin/com/ivata/groupware/web/tree/person/.*
- ./addressbook/jar/.*
- ./addressbook/lib/.*
- ./addressbook/war/.*
- ./build/.*
- ./build/bin/.*
- ./build/bin/eclipse/.*
- ./build/bin/sh/.*
- ./build/bin/xslt/.*
- ./calendar/.*
- ./calendar/bin/.*
- ./calendar/bin/com/.*
- ./calendar/bin/com/ivata/.*
- ./calendar/bin/com/ivata/groupware/.*
- ./calendar/bin/com/ivata/groupware/business/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/event/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/event/meeting/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/event/meeting/agendapoint/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/event/meeting/attendee/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/event/meeting/category/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/event/publicholiday/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/event/vacation/.*
- ./calendar/bin/com/ivata/groupware/business/calendar/struts/.*
- ./calendar/jar/.*
- ./calendar/lib/.*
- ./calendar/war/.*
- ./core/.*
- ./core/bin/.*
- ./core/bin/com/.*
- ./core/bin/com/ivata/.*
- ./core/bin/com/ivata/groupware/.*
- ./core/bin/com/ivata/groupware/business/.*
- ./core/bin/com/ivata/groupware/business/event/.*
- ./core/bin/com/ivata/groupware/container/.*
- ./core/bin/com/ivata/groupware/container/persistence/.*
- ./core/bin/com/ivata/groupware/container/persistence/hibernate/.*
- ./core/bin/com/ivata/groupware/container/persistence/listener/.*
- ./core/bin/com/ivata/groupware/container/struts/.*
- ./core/bin/com/ivata/groupware/struts/.*
- ./core/jar/.*
- ./core/lib/.*
- ./core/war/.*
- ./hibernate/.*
- ./hibernate/export/.*
- ./htmlparser/.*
- ./htmlparser/bin/.*
- ./htmlparser/bin/com/.*
- ./htmlparser/bin/com/ivata/.*
- ./htmlparser/bin/com/ivata/groupware/.*
- ./htmlparser/bin/com/ivata/groupware/web/.*
- ./htmlparser/bin/com/ivata/groupware/web/format/.*
- ./htmlparser/jar/.*
- ./htmlparser/lib/.*
- ./library/.*
- ./library/bin/.*
- ./library/bin/com/.*
- ./library/bin/com/ivata/.*
- ./library/bin/com/ivata/groupware/.*
- ./library/bin/com/ivata/groupware/business/.*
- ./library/bin/com/ivata/groupware/business/drive/.*
- ./library/bin/com/ivata/groupware/business/drive/directory/.*
- ./library/bin/com/ivata/groupware/business/drive/file/.*
- ./library/bin/com/ivata/groupware/business/library/.*
- ./library/bin/com/ivata/groupware/business/library/comment/.*
- ./library/bin/com/ivata/groupware/business/library/comment/tree/.*
- ./library/bin/com/ivata/groupware/business/library/faq/.*
- ./library/bin/com/ivata/groupware/business/library/faq/category/.*
- ./library/bin/com/ivata/groupware/business/library/item/.*
- ./library/bin/com/ivata/groupware/business/library/listener/.*
- ./library/bin/com/ivata/groupware/business/library/page/.*
- ./library/bin/com/ivata/groupware/business/library/right/.*
- ./library/bin/com/ivata/groupware/business/library/struts/.*
- ./library/bin/com/ivata/groupware/business/library/topic/.*
- ./library/bin/com/ivata/groupware/web/.*
- ./library/bin/com/ivata/groupware/web/servlet/.*
- ./library/bin/com/ivata/groupware/web/tree/.*
- ./library/bin/com/ivata/groupware/web/tree/comment/.*
- ./library/jar/.*
- ./library/lib/.*
- ./library/war/.*
- ./mask/.*
- ./mask/bin/.*
- ./mask/bin/com/.*
- ./mask/bin/com/ivata/.*
- ./mask/bin/com/ivata/groupware/.*
- ./mask/bin/com/ivata/groupware/container/.*
- ./mask/bin/com/ivata/groupware/container/struts/.*
- ./mask/bin/com/ivata/groupware/mask/.*
- ./mask/bin/com/ivata/groupware/mask/struts/.*
- ./mask/jar/.*
- ./mask/lib/.*
- ./package/.*
- ./package/install/.*
- ./package/startdb/.*
- ./package/war/.*
- ./search/.*
- ./search/bin/.*
- ./search/bin/com/.*
- ./search/bin/com/ivata/.*
- ./search/bin/com/ivata/groupware/.*
- ./search/bin/com/ivata/groupware/business/.*
- ./search/bin/com/ivata/groupware/business/search/.*
- ./search/bin/com/ivata/groupware/business/search/index/.*
- ./search/bin/com/ivata/groupware/business/search/item/.*
- ./search/bin/com/ivata/groupware/business/search/item/content/.*
- ./search/bin/com/ivata/groupware/business/search/result/.*
- ./search/bin/com/ivata/groupware/business/search/stopword/.*
- ./search/jar/.*
- ./search/lib/.*
- ./security/.*
- ./security/bin/.*
- ./security/bin/com/.*
- ./security/bin/com/ivata/.*
- ./security/bin/com/ivata/groupware/.*
- ./security/bin/com/ivata/groupware/admin/.*
- ./security/bin/com/ivata/groupware/admin/script/.*
- ./security/bin/com/ivata/groupware/admin/security/.*
- ./security/bin/com/ivata/groupware/admin/security/server/.*
- ./security/bin/com/ivata/groupware/admin/security/struts/.*
- ./security/bin/com/ivata/groupware/admin/security/user/.*
- ./security/bin/com/ivata/groupware/admin/setting/.*
- ./security/bin/com/ivata/groupware/admin/struts/.*
- ./security/bin/com/ivata/groupware/business/.*
- ./security/bin/com/ivata/groupware/container/.*
- ./security/bin/com/ivata/groupware/container/persistence/.*
- ./security/bin/com/ivata/groupware/navigation/.*
- ./security/bin/com/ivata/groupware/navigation/menu/.*
- ./security/bin/com/ivata/groupware/navigation/menu/item/.*
- ./security/bin/com/ivata/groupware/navigation/menu/item/listener/.*
- ./security/bin/com/ivata/groupware/util/.*
- ./security/bin/com/ivata/groupware/web/.*
- ./security/bin/com/ivata/groupware/web/container/.*
- ./security/bin/com/ivata/groupware/web/format/.*
- ./security/bin/com/ivata/groupware/web/tag/.*
- ./security/bin/com/ivata/groupware/web/tag/container/.*
- ./security/jar/.*
- ./security/lib/.*
- ./webmail/.*
- ./webmail/bin/.*
- ./webmail/bin/com/.*
- ./webmail/bin/com/ivata/.*
- ./webmail/bin/com/ivata/groupware/.*
- ./webmail/bin/com/ivata/groupware/business/.*
- ./webmail/bin/com/ivata/groupware/business/drive/.*
- ./webmail/bin/com/ivata/groupware/business/drive/file/.*
- ./webmail/bin/com/ivata/groupware/business/mail/.*
- ./webmail/bin/com/ivata/groupware/business/mail/message/.*
- ./webmail/bin/com/ivata/groupware/business/mail/server/.*
- ./webmail/bin/com/ivata/groupware/business/mail/session/.*
- ./webmail/bin/com/ivata/groupware/business/mail/struts/.*
- ./webmail/jar/.*
- ./webmail/lib/.*
- ./webmail/war/.*
